# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 359)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.l_a = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_a.setFont(font)
        self.l_a.setAlignment(QtCore.Qt.AlignCenter)
        self.l_a.setObjectName("l_a")
        self.verticalLayout_2.addWidget(self.l_a)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.l_b = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_b.setFont(font)
        self.l_b.setAlignment(QtCore.Qt.AlignCenter)
        self.l_b.setObjectName("l_b")
        self.verticalLayout_3.addWidget(self.l_b)
        self.gridLayout.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_c = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_c.setFont(font)
        self.l_c.setAlignment(QtCore.Qt.AlignCenter)
        self.l_c.setObjectName("l_c")
        self.verticalLayout.addWidget(self.l_c)
        self.gridLayout.addWidget(self.groupBox, 0, 2, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.l_d = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_d.setFont(font)
        self.l_d.setAlignment(QtCore.Qt.AlignCenter)
        self.l_d.setObjectName("l_d")
        self.verticalLayout_8.addWidget(self.l_d)
        self.gridLayout.addWidget(self.groupBox_8, 0, 3, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.l_e = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_e.setFont(font)
        self.l_e.setAlignment(QtCore.Qt.AlignCenter)
        self.l_e.setObjectName("l_e")
        self.verticalLayout_9.addWidget(self.l_e)
        self.gridLayout.addWidget(self.groupBox_9, 0, 4, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.l_f = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_f.setFont(font)
        self.l_f.setAlignment(QtCore.Qt.AlignCenter)
        self.l_f.setObjectName("l_f")
        self.verticalLayout_4.addWidget(self.l_f)
        self.gridLayout.addWidget(self.groupBox_4, 0, 5, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.l_g = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_g.setFont(font)
        self.l_g.setAlignment(QtCore.Qt.AlignCenter)
        self.l_g.setObjectName("l_g")
        self.verticalLayout_5.addWidget(self.l_g)
        self.gridLayout.addWidget(self.groupBox_5, 0, 6, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.l_h = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_h.setFont(font)
        self.l_h.setAlignment(QtCore.Qt.AlignCenter)
        self.l_h.setObjectName("l_h")
        self.verticalLayout_6.addWidget(self.l_h)
        self.gridLayout.addWidget(self.groupBox_6, 0, 7, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.l_i = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_i.setFont(font)
        self.l_i.setAlignment(QtCore.Qt.AlignCenter)
        self.l_i.setObjectName("l_i")
        self.verticalLayout_15.addWidget(self.l_i)
        self.gridLayout.addWidget(self.groupBox_15, 0, 8, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.l_j = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_j.setFont(font)
        self.l_j.setAlignment(QtCore.Qt.AlignCenter)
        self.l_j.setObjectName("l_j")
        self.verticalLayout_10.addWidget(self.l_j)
        self.gridLayout.addWidget(self.groupBox_10, 1, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.l_k = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_k.setFont(font)
        self.l_k.setAlignment(QtCore.Qt.AlignCenter)
        self.l_k.setObjectName("l_k")
        self.verticalLayout_11.addWidget(self.l_k)
        self.gridLayout.addWidget(self.groupBox_11, 1, 1, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.l_l = QtWidgets.QLabel(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_l.setFont(font)
        self.l_l.setAlignment(QtCore.Qt.AlignCenter)
        self.l_l.setObjectName("l_l")
        self.verticalLayout_14.addWidget(self.l_l)
        self.gridLayout.addWidget(self.groupBox_14, 1, 2, 1, 1)
        self.groupBox_21 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_21.setFont(font)
        self.groupBox_21.setObjectName("groupBox_21")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.groupBox_21)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.l_m = QtWidgets.QLabel(self.groupBox_21)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_m.setFont(font)
        self.l_m.setAlignment(QtCore.Qt.AlignCenter)
        self.l_m.setObjectName("l_m")
        self.verticalLayout_21.addWidget(self.l_m)
        self.gridLayout.addWidget(self.groupBox_21, 1, 3, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_20.setFont(font)
        self.groupBox_20.setObjectName("groupBox_20")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_20)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.l_y = QtWidgets.QLabel(self.groupBox_20)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_y.setFont(font)
        self.l_y.setAlignment(QtCore.Qt.AlignCenter)
        self.l_y.setObjectName("l_y")
        self.verticalLayout_20.addWidget(self.l_y)
        self.gridLayout.addWidget(self.groupBox_20, 2, 6, 1, 1)
        self.groupBox_26 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_26.setFont(font)
        self.groupBox_26.setObjectName("groupBox_26")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.groupBox_26)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.l_z = QtWidgets.QLabel(self.groupBox_26)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_z.setFont(font)
        self.l_z.setAlignment(QtCore.Qt.AlignCenter)
        self.l_z.setObjectName("l_z")
        self.verticalLayout_28.addWidget(self.l_z)
        self.gridLayout.addWidget(self.groupBox_26, 2, 7, 1, 1)
        self.groupBox_16 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.l_x = QtWidgets.QLabel(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_x.setFont(font)
        self.l_x.setAlignment(QtCore.Qt.AlignCenter)
        self.l_x.setObjectName("l_x")
        self.verticalLayout_16.addWidget(self.l_x)
        self.gridLayout.addWidget(self.groupBox_16, 2, 5, 1, 1)
        self.groupBox_22 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_22.setFont(font)
        self.groupBox_22.setObjectName("groupBox_22")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.groupBox_22)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.l_w = QtWidgets.QLabel(self.groupBox_22)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_w.setFont(font)
        self.l_w.setAlignment(QtCore.Qt.AlignCenter)
        self.l_w.setObjectName("l_w")
        self.verticalLayout_22.addWidget(self.l_w)
        self.gridLayout.addWidget(self.groupBox_22, 2, 4, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.l_v = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_v.setFont(font)
        self.l_v.setAlignment(QtCore.Qt.AlignCenter)
        self.l_v.setObjectName("l_v")
        self.verticalLayout_17.addWidget(self.l_v)
        self.gridLayout.addWidget(self.groupBox_17, 2, 3, 1, 1)
        self.groupBox_18 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.l_u = QtWidgets.QLabel(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_u.setFont(font)
        self.l_u.setAlignment(QtCore.Qt.AlignCenter)
        self.l_u.setObjectName("l_u")
        self.verticalLayout_18.addWidget(self.l_u)
        self.gridLayout.addWidget(self.groupBox_18, 2, 2, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.l_t = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_t.setFont(font)
        self.l_t.setAlignment(QtCore.Qt.AlignCenter)
        self.l_t.setObjectName("l_t")
        self.verticalLayout_7.addWidget(self.l_t)
        self.gridLayout.addWidget(self.groupBox_7, 2, 1, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.l_s = QtWidgets.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_s.setFont(font)
        self.l_s.setAlignment(QtCore.Qt.AlignCenter)
        self.l_s.setObjectName("l_s")
        self.verticalLayout_13.addWidget(self.l_s)
        self.gridLayout.addWidget(self.groupBox_13, 2, 0, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_19.setFont(font)
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.l_r = QtWidgets.QLabel(self.groupBox_19)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_r.setFont(font)
        self.l_r.setAlignment(QtCore.Qt.AlignCenter)
        self.l_r.setObjectName("l_r")
        self.verticalLayout_19.addWidget(self.l_r)
        self.gridLayout.addWidget(self.groupBox_19, 1, 8, 1, 1)
        self.groupBox_24 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_24.setFont(font)
        self.groupBox_24.setObjectName("groupBox_24")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.groupBox_24)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.l_q = QtWidgets.QLabel(self.groupBox_24)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_q.setFont(font)
        self.l_q.setAlignment(QtCore.Qt.AlignCenter)
        self.l_q.setObjectName("l_q")
        self.verticalLayout_24.addWidget(self.l_q)
        self.gridLayout.addWidget(self.groupBox_24, 1, 7, 1, 1)
        self.groupBox_25 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_25.setFont(font)
        self.groupBox_25.setObjectName("groupBox_25")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.groupBox_25)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.l_p = QtWidgets.QLabel(self.groupBox_25)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_p.setFont(font)
        self.l_p.setAlignment(QtCore.Qt.AlignCenter)
        self.l_p.setObjectName("l_p")
        self.verticalLayout_25.addWidget(self.l_p)
        self.gridLayout.addWidget(self.groupBox_25, 1, 6, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.l_o = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_o.setFont(font)
        self.l_o.setAlignment(QtCore.Qt.AlignCenter)
        self.l_o.setObjectName("l_o")
        self.verticalLayout_12.addWidget(self.l_o)
        self.gridLayout.addWidget(self.groupBox_12, 1, 5, 1, 1)
        self.groupBox_23 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_23.setFont(font)
        self.groupBox_23.setObjectName("groupBox_23")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.groupBox_23)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.l_n = QtWidgets.QLabel(self.groupBox_23)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.l_n.setFont(font)
        self.l_n.setAlignment(QtCore.Qt.AlignCenter)
        self.l_n.setObjectName("l_n")
        self.verticalLayout_23.addWidget(self.l_n)
        self.gridLayout.addWidget(self.groupBox_23, 1, 4, 1, 1)
        self.verticalLayout_27.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_text = QtWidgets.QLineEdit(self.frame_2)
        self.edit_text.setObjectName("edit_text")
        self.horizontalLayout.addWidget(self.edit_text)
        self.btn_send = QtWidgets.QPushButton(self.frame_2)
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout.addWidget(self.btn_send)
        self.verticalLayout_27.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lab 6"))
        self.groupBox_2.setTitle(_translate("MainWindow", "A"))
        self.l_a.setText(_translate("MainWindow", "0"))
        self.groupBox_3.setTitle(_translate("MainWindow", "B"))
        self.l_b.setText(_translate("MainWindow", "0"))
        self.groupBox.setTitle(_translate("MainWindow", "C"))
        self.l_c.setText(_translate("MainWindow", "0"))
        self.groupBox_8.setTitle(_translate("MainWindow", "D"))
        self.l_d.setText(_translate("MainWindow", "0"))
        self.groupBox_9.setTitle(_translate("MainWindow", "E"))
        self.l_e.setText(_translate("MainWindow", "0"))
        self.groupBox_4.setTitle(_translate("MainWindow", "F"))
        self.l_f.setText(_translate("MainWindow", "0"))
        self.groupBox_5.setTitle(_translate("MainWindow", "G"))
        self.l_g.setText(_translate("MainWindow", "0"))
        self.groupBox_6.setTitle(_translate("MainWindow", "H"))
        self.l_h.setText(_translate("MainWindow", "0"))
        self.groupBox_15.setTitle(_translate("MainWindow", "I"))
        self.l_i.setText(_translate("MainWindow", "0"))
        self.groupBox_10.setTitle(_translate("MainWindow", "J"))
        self.l_j.setText(_translate("MainWindow", "0"))
        self.groupBox_11.setTitle(_translate("MainWindow", "K"))
        self.l_k.setText(_translate("MainWindow", "0"))
        self.groupBox_14.setTitle(_translate("MainWindow", "L"))
        self.l_l.setText(_translate("MainWindow", "0"))
        self.groupBox_21.setTitle(_translate("MainWindow", "M"))
        self.l_m.setText(_translate("MainWindow", "0"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Y"))
        self.l_y.setText(_translate("MainWindow", "0"))
        self.groupBox_26.setTitle(_translate("MainWindow", "Z"))
        self.l_z.setText(_translate("MainWindow", "0"))
        self.groupBox_16.setTitle(_translate("MainWindow", "X"))
        self.l_x.setText(_translate("MainWindow", "0"))
        self.groupBox_22.setTitle(_translate("MainWindow", "W"))
        self.l_w.setText(_translate("MainWindow", "0"))
        self.groupBox_17.setTitle(_translate("MainWindow", "V"))
        self.l_v.setText(_translate("MainWindow", "0"))
        self.groupBox_18.setTitle(_translate("MainWindow", "U"))
        self.l_u.setText(_translate("MainWindow", "0"))
        self.groupBox_7.setTitle(_translate("MainWindow", "T"))
        self.l_t.setText(_translate("MainWindow", "0"))
        self.groupBox_13.setTitle(_translate("MainWindow", "S"))
        self.l_s.setText(_translate("MainWindow", "0"))
        self.groupBox_19.setTitle(_translate("MainWindow", "R"))
        self.l_r.setText(_translate("MainWindow", "0"))
        self.groupBox_24.setTitle(_translate("MainWindow", "Q"))
        self.l_q.setText(_translate("MainWindow", "0"))
        self.groupBox_25.setTitle(_translate("MainWindow", "P"))
        self.l_p.setText(_translate("MainWindow", "0"))
        self.groupBox_12.setTitle(_translate("MainWindow", "O"))
        self.l_o.setText(_translate("MainWindow", "0"))
        self.groupBox_23.setTitle(_translate("MainWindow", "N"))
        self.l_n.setText(_translate("MainWindow", "0"))
        self.btn_send.setText(_translate("MainWindow", "Отправить"))
