# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\edit.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Edit_Form(object):
    def setupUi(self, Edit_Form):
        Edit_Form.setObjectName("Edit_Form")
        Edit_Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Edit_Form.resize(330, 693)
        self.verticalLayout = QtWidgets.QVBoxLayout(Edit_Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_type_box = QtWidgets.QFrame(Edit_Form)
        self.input_type_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_type_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_type_box.setObjectName("input_type_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.input_type_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.input_type_box)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.edit_type = QtWidgets.QLineEdit(self.input_type_box)
        self.edit_type.setObjectName("edit_type")
        self.verticalLayout_2.addWidget(self.edit_type)
        self.verticalLayout.addWidget(self.input_type_box)
        self.input_nick_box = QtWidgets.QFrame(Edit_Form)
        self.input_nick_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_nick_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_nick_box.setObjectName("input_nick_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.input_nick_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.input_nick_box)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.edit_nick = QtWidgets.QLineEdit(self.input_nick_box)
        self.edit_nick.setObjectName("edit_nick")
        self.verticalLayout_3.addWidget(self.edit_nick)
        self.verticalLayout.addWidget(self.input_nick_box)
        self.input_color_box = QtWidgets.QFrame(Edit_Form)
        self.input_color_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_color_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_color_box.setObjectName("input_color_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.input_color_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.input_color_box)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.box_color_2 = QtWidgets.QComboBox(self.input_color_box)
        self.box_color_2.setObjectName("box_color_2")
        self.box_color_2.addItem("")
        self.box_color_2.addItem("")
        self.box_color_2.addItem("")
        self.box_color_2.addItem("")
        self.box_color_2.addItem("")
        self.box_color_2.addItem("")
        self.verticalLayout_5.addWidget(self.box_color_2)
        self.verticalLayout.addWidget(self.input_color_box)
        self.input_birthday_box = QtWidgets.QFrame(Edit_Form)
        self.input_birthday_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_birthday_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_birthday_box.setObjectName("input_birthday_box")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.input_birthday_box)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.input_birthday_box)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.dateEdit = QtWidgets.QDateEdit(self.input_birthday_box)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_6.addWidget(self.dateEdit)
        self.verticalLayout.addWidget(self.input_birthday_box)
        self.input_owner_box = QtWidgets.QFrame(Edit_Form)
        self.input_owner_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_owner_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_owner_box.setObjectName("input_owner_box")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.input_owner_box)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.input_owner_box)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.edit_owner = QtWidgets.QLineEdit(self.input_owner_box)
        self.edit_owner.setObjectName("edit_owner")
        self.verticalLayout_7.addWidget(self.edit_owner)
        self.verticalLayout.addWidget(self.input_owner_box)
        self.input_phone_box = QtWidgets.QFrame(Edit_Form)
        self.input_phone_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_phone_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_phone_box.setObjectName("input_phone_box")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.input_phone_box)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.input_phone_box)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.edit_phone = QtWidgets.QLineEdit(self.input_phone_box)
        self.edit_phone.setObjectName("edit_phone")
        self.verticalLayout_8.addWidget(self.edit_phone)
        self.verticalLayout.addWidget(self.input_phone_box)
        self.frame = QtWidgets.QFrame(Edit_Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_edit = QtWidgets.QPushButton(self.frame)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout.addWidget(self.btn_edit)
        self.btn_cancel = QtWidgets.QPushButton(self.frame)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Edit_Form)
        QtCore.QMetaObject.connectSlotsByName(Edit_Form)

    def retranslateUi(self, Edit_Form):
        _translate = QtCore.QCoreApplication.translate
        Edit_Form.setWindowTitle(_translate("Edit_Form", "Изменение"))
        self.label_2.setText(_translate("Edit_Form", "Вид"))
        self.label_3.setText(_translate("Edit_Form", "Кличка"))
        self.label_5.setText(_translate("Edit_Form", "Окрас шерсти"))
        self.box_color_2.setItemText(0, _translate("Edit_Form", "Белый"))
        self.box_color_2.setItemText(1, _translate("Edit_Form", "Чёрный"))
        self.box_color_2.setItemText(2, _translate("Edit_Form", "Серый"))
        self.box_color_2.setItemText(3, _translate("Edit_Form", "Коричневый"))
        self.box_color_2.setItemText(4, _translate("Edit_Form", "Рыжий"))
        self.box_color_2.setItemText(5, _translate("Edit_Form", "Другое"))
        self.label_8.setText(_translate("Edit_Form", "Дата рождения"))
        self.label_6.setText(_translate("Edit_Form", "ФИО владельца"))
        self.label_7.setText(_translate("Edit_Form", "Телефон владельца"))
        self.btn_edit.setText(_translate("Edit_Form", "Изменить"))
        self.btn_cancel.setText(_translate("Edit_Form", "Отмена"))
