# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab4\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1037, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout_2.setObjectName("formLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_id_box = QtWidgets.QFrame(self.frame)
        self.input_id_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_id_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_id_box.setObjectName("input_id_box")
        self.gridLayout = QtWidgets.QGridLayout(self.input_id_box)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.input_id_box)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.edit_id = QtWidgets.QLineEdit(self.input_id_box)
        self.edit_id.setObjectName("edit_id")
        self.gridLayout.addWidget(self.edit_id, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.input_id_box)
        self.input_type_box = QtWidgets.QFrame(self.frame)
        self.input_type_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_type_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_type_box.setObjectName("input_type_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.input_type_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.input_type_box)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.edit_type = QtWidgets.QLineEdit(self.input_type_box)
        self.edit_type.setObjectName("edit_type")
        self.verticalLayout_2.addWidget(self.edit_type)
        self.verticalLayout.addWidget(self.input_type_box)
        self.input_nick_box = QtWidgets.QFrame(self.frame)
        self.input_nick_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_nick_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_nick_box.setObjectName("input_nick_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.input_nick_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.input_nick_box)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.edit_nick = QtWidgets.QLineEdit(self.input_nick_box)
        self.edit_nick.setObjectName("edit_nick")
        self.verticalLayout_3.addWidget(self.edit_nick)
        self.verticalLayout.addWidget(self.input_nick_box)
        self.input_color_box = QtWidgets.QFrame(self.frame)
        self.input_color_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_color_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_color_box.setObjectName("input_color_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.input_color_box)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.input_color_box)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.box_color = QtWidgets.QComboBox(self.input_color_box)
        self.box_color.setObjectName("box_color")
        self.box_color.addItem("")
        self.box_color.addItem("")
        self.box_color.addItem("")
        self.box_color.addItem("")
        self.box_color.addItem("")
        self.box_color.addItem("")
        self.verticalLayout_4.addWidget(self.box_color)
        self.verticalLayout.addWidget(self.input_color_box)
        self.input_birthday_box = QtWidgets.QFrame(self.frame)
        self.input_birthday_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_birthday_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_birthday_box.setObjectName("input_birthday_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.input_birthday_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.input_birthday_box)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.dateEdit = QtWidgets.QDateEdit(self.input_birthday_box)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_5.addWidget(self.dateEdit)
        self.verticalLayout.addWidget(self.input_birthday_box)
        self.input_owner_box = QtWidgets.QFrame(self.frame)
        self.input_owner_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_owner_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_owner_box.setObjectName("input_owner_box")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.input_owner_box)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.input_owner_box)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.edit_owner = QtWidgets.QLineEdit(self.input_owner_box)
        self.edit_owner.setObjectName("edit_owner")
        self.verticalLayout_7.addWidget(self.edit_owner)
        self.verticalLayout.addWidget(self.input_owner_box)
        self.input_phone_box = QtWidgets.QFrame(self.frame)
        self.input_phone_box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_phone_box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_phone_box.setObjectName("input_phone_box")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.input_phone_box)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.input_phone_box)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.edit_phone = QtWidgets.QLineEdit(self.input_phone_box)
        self.edit_phone.setObjectName("edit_phone")
        self.verticalLayout_8.addWidget(self.edit_phone)
        self.verticalLayout.addWidget(self.input_phone_box)
        self.btns_frame = QtWidgets.QFrame(self.frame)
        self.btns_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btns_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btns_frame.setObjectName("btns_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.btns_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAdd = QtWidgets.QPushButton(self.btns_frame)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.btnClear = QtWidgets.QPushButton(self.btns_frame)
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout.addWidget(self.btnClear)
        self.verticalLayout.addWidget(self.btns_frame)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frame)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mainTable = QtWidgets.QTableWidget(self.frame_3)
        self.mainTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.mainTable.setShowGrid(True)
        self.mainTable.setObjectName("mainTable")
        self.mainTable.setColumnCount(7)
        self.mainTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(6, item)
        self.mainTable.horizontalHeader().setVisible(True)
        self.mainTable.horizontalHeader().setCascadingSectionResizes(True)
        self.mainTable.horizontalHeader().setSortIndicatorShown(False)
        self.mainTable.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_6.addWidget(self.mainTable)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.cbAll = QtWidgets.QCheckBox(self.frame_2)
        self.cbAll.setObjectName("cbAll")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cbAll)
        self.btnDelete = QtWidgets.QPushButton(self.frame_2)
        self.btnDelete.setObjectName("btnDelete")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.btnDelete)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1037, 26))
        self.menuBar.setObjectName("menuBar")
        self.mainMenu = QtWidgets.QMenu(self.menuBar)
        self.mainMenu.setTearOffEnabled(False)
        self.mainMenu.setObjectName("mainMenu")
        MainWindow.setMenuBar(self.menuBar)
        self.searchAct = QtWidgets.QAction(MainWindow)
        self.searchAct.setObjectName("searchAct")
        self.mainMenu.addAction(self.searchAct)
        self.menuBar.addAction(self.mainMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.btnClear.clicked.connect(self.edit_phone.clear)
        self.btnClear.clicked.connect(self.edit_owner.clear)
        self.btnClear.clicked.connect(self.edit_nick.clear)
        self.btnClear.clicked.connect(self.edit_type.clear)
        self.btnClear.clicked.connect(self.edit_id.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lab 4"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.label_2.setText(_translate("MainWindow", "Вид"))
        self.label_3.setText(_translate("MainWindow", "Кличка"))
        self.label_4.setText(_translate("MainWindow", "Окрас шерсти"))
        self.box_color.setItemText(0, _translate("MainWindow", "Белый"))
        self.box_color.setItemText(1, _translate("MainWindow", "Чёрный"))
        self.box_color.setItemText(2, _translate("MainWindow", "Серый"))
        self.box_color.setItemText(3, _translate("MainWindow", "Коричневый"))
        self.box_color.setItemText(4, _translate("MainWindow", "Рыжий"))
        self.box_color.setItemText(5, _translate("MainWindow", "Другое"))
        self.label_5.setText(_translate("MainWindow", "Дата рождения"))
        self.label_6.setText(_translate("MainWindow", "ФИО владельца"))
        self.label_7.setText(_translate("MainWindow", "Телефон владельца"))
        self.btnAdd.setText(_translate("MainWindow", "Добавить"))
        self.btnClear.setText(_translate("MainWindow", "Очистить"))
        item = self.mainTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.mainTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Вид"))
        item = self.mainTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Кличка"))
        item = self.mainTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Окрас шерсти"))
        item = self.mainTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Дата рождения"))
        item = self.mainTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ФИО владельца"))
        item = self.mainTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Телефон владельца"))
        self.cbAll.setText(_translate("MainWindow", "Всё"))
        self.btnDelete.setText(_translate("MainWindow", "Удалить"))
        self.mainMenu.setTitle(_translate("MainWindow", "Меню"))
        self.searchAct.setText(_translate("MainWindow", "Поиск"))
